### PR TITLE
.gitmodules & README: Add docson to submodules list, update README

### PR DESCRIPTION
**Pull request by robredpath**
Just adding this as it would have been handy for the work I'm currently doing

### CODE REVIEW

**Comment by robredpath** [comment]
I guess an example would be in order, actually.

**Comment by robredpath** [comment]
(also, FINALLY a formal way of marking things as WIP in GH!)

**Comment by Bjwebb** [comment]
Looking good so far. An example would be great.

**Comment by robredpath** [comment]
I tried to add an example, but somewhere my <script> tag got stripped out. Any idea why that might happen, @Bjwebb ?

**Comment by Bjwebb** [comment]
Not sure exactly why. I can try different recommonmark versions, to see if that makes a difference.

**Comment by Bjwebb** [comment]
Yes, it appears to be a matter of the recommonmark version. OCDS currently uses a hotfix branch in a fork repo — looks like its a merge of 4 PR branches, of which only one has made its way into master (since November). Its probably worth switching to this, but it might be useful to spend a bit of time understanding what we're getting ourselves into.

**Comment by Bjwebb** [comment]
For now i've just switched to the latest recommonmark pypi package, and updated the other requirements. The script tag works now if you rebase on the latest master.

**Comment by robredpath** [comment]
@Bjwebb can you review again? I've added an example, that works now (thanks!)

**Review by Bjwebb — APPROVED** [review]

**Pull request merged**
